[package]
name = "integra_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
integra = { version = "0.0.8" }
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14" }